config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors

  resources :especialidads
  resources :servicios

  
  root to: 'pages#home'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :servicios

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/esp_list.rb
class EspList < ApplicationRecord
  belongs_to :especialidad
  belongs_to :list
end

app/models/especialidad.rb
class Especialidad < ApplicationRecord
  belongs_to :doctor

  has_many :esp_list
  has_many :list, through: :esp_list
end

app/models/list.rb
class List < ApplicationRecord
    has_many :esp_list
    has_many :especialidads, through: :esp_list
end

app/models/servicio.rb
class Servicio < ApplicationRecord
  belongs_to :doctor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permited_parameters, if: :devise_controller?

    private
    def configure_permited_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :apellido, :edad, :foto])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :apellido, :edad, :foto])
    end

end

app/controllers/doctors/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/especialidads_controller.rb
class EspecialidadsController < ApplicationController
  before_action :set_especialidad, only: %i[ show edit update destroy ]

  # GET /especialidads or /especialidads.json
  def index
    @especialidads = Especialidad.all
  end

  # GET /especialidads/1 or /especialidads/1.json
  def show
  end

  # GET /especialidads/new
  def new
    @especialidad = Especialidad.new
  end

  # GET /especialidads/1/edit
  def edit
  end

  # POST /especialidads or /especialidads.json
  def create
    @especialidad = Especialidad.new(especialidad_params)

    respond_to do |format|
      if @especialidad.save
        format.html { redirect_to especialidad_url(@especialidad), notice: "Especialidad was successfully created." }
        format.json { render :show, status: :created, location: @especialidad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidads/1 or /especialidads/1.json
  def update
    respond_to do |format|
      if @especialidad.update(especialidad_params)
        format.html { redirect_to especialidad_url(@especialidad), notice: "Especialidad was successfully updated." }
        format.json { render :show, status: :ok, location: @especialidad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidads/1 or /especialidads/1.json
  def destroy
    @especialidad.destroy

    respond_to do |format|
      format.html { redirect_to especialidads_url, notice: "Especialidad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidad
      @especialidad = Especialidad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def especialidad_params
      params.require(:especialidad).permit(:name, :doctor_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :set_servicio, only: %i[ show edit update destroy ]

  # GET /servicios or /servicios.json
  def index
    @servicios = Servicio.all
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'servicios/impreso' }
    end

  end

  # GET /servicios/1 or /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
    @servicio = Servicio.new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios or /servicios.json
  def create
    @servicio = Servicio.new(servicio_params)

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to servicio_url(@servicio), notice: "Servicio was successfully created." }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1 or /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to servicio_url(@servicio), notice: "Servicio was successfully updated." }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1 or /servicios/1.json
  def destroy
    @servicio.destroy

    respond_to do |format|
      format.html { redirect_to servicios_url, notice: "Servicio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio
      @servicio = Servicio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def servicio_params
      params.require(:servicio).permit(:nombre, :precio, :doctor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/especialidads_helper.rb
module EspecialidadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/especialidads/_especialidad.html.erb
<div id="<%= dom_id especialidad %>">
  <p>
    <strong>Name:</strong>
    <%= List.all.find(especialidad.name).name %>
    <% especialidad.name %>
  </p>

  <p>
    <strong>Doctor:</strong>
    <%= especialidad.doctor_id %>
  </p>

</div>

app/views/especialidads/_form.html.erb
<%= form_with(model: especialidad) do |form| %>
  <% if especialidad.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(especialidad.errors.count, "error") %> prohibited this especialidad from being saved:</h2>

      <ul>
        <% especialidad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%# form.text_field :name %>
    <%= form.select :name, List.pluck(:name, :id) %>
  </div>

  <div>
    <%= form.text_field :doctor_id, value: current_doctor.id, type: "hidden" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary btnSubmit" %>
  </div>
<% end %>

app/views/especialidads/edit.html.erb
<h1>Editing especialidad</h1>

<%= render "form", especialidad: @especialidad %>

<br>

<div>
  <%= link_to "Show this especialidad", @especialidad %> |
  <%= link_to "Back to especialidads", especialidads_path %>
</div>

app/views/especialidads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Especialidads</h1>

<div id="especialidads">
  <% @especialidads.each do |especialidad| %>
    <% if(especialidad.doctor_id == current_doctor.id )%>
      <%= render especialidad %>
      <p>
        <%= link_to "Show", especialidad %>
      </p>
    <% end %>
      
  <% end %>
</div>

<%= link_to "Añadir especialidad", new_especialidad_path, class:"btnAnadir btn btn-primary" %>


<%# if( List.all.find(current_doctor.id) ) %>
<%# end %>

app/views/especialidads/new.html.erb
<h1>New especialidad</h1>

<%= render "form", especialidad: @especialidad %>

<br>

<div>
  <%= link_to "Back to especialidads", especialidads_path %>
</div>

app/views/especialidads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @especialidad %>

<div>
  <%= link_to "Edit", edit_especialidad_path(@especialidad) %> |
  <%= link_to "Back", especialidads_path %>

  <%= button_to "Destroy", @especialidad, method: :delete, class:"btnD btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TechProject</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  
  </head>
  <body>
    <%= render "shared/header" %>

    <div class="container main">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    
        <%= yield %>
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= current_doctor.inspect %>

app/views/servicios/_form.html.erb
<%= form_with(model: servicio) do |form| %>
  <% if servicio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(servicio.errors.count, "error") %> prohibited this servicio from being saved:</h2>

      <ul>
        <% servicio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio %>
  </div>

  <div>
    <%= form.text_field :doctor_id, value: current_doctor.id, type:"hidden" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/servicios/_servicio.html.erb
<div id="<%= dom_id servicio %>">
  <p>
    <strong>Nombre:</strong>
    <%= servicio.nombre %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= servicio.precio %>
  </p>

  <p>
    <strong>Doctor:</strong>
    <%= servicio.doctor_id %>
  </p>

</div>

app/views/servicios/edit.html.erb
<h1>Editing servicio</h1>

<%= render "form", servicio: @servicio %>

<br>

<div>
  <%= link_to "Show this servicio", @servicio %> |
  <%= link_to "Back to servicios", servicios_path %>
</div>

app/views/servicios/impreso.pdf.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
            </tr>
        </thead>

        <tbody>
            <% @servicios.each do |servicio| %>
                <% if(current_doctor.id == servicio.doctor_id) %>
                    <tr>
                        <th><%= servicio.nombre %></th>
                        <th><%= servicio.precio %></th>
                    </tr>
                <% end %>
            <% end %>
        </tbody>

    </table>
</body>
</html>

app/views/servicios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Servicios</h1>

<div id="servicios">
  <% @servicios.each do |servicio| %>
    <% if(current_doctor.id == servicio.doctor_id) %>
      <%= render servicio %>
      <p>
        <%= link_to "Show this servicio", servicio %>
      </p>
    <% end %>
  <% end %>
</div>

<%= link_to "New servicio", new_servicio_path %>

app/views/servicios/new.html.erb
<h1>New servicio</h1>

<%= render "form", servicio: @servicio %>

<br>

<div>
  <%= link_to "Back to servicios", servicios_path %>
</div>

app/views/servicios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @servicio %>

<div>
  <%= link_to "Edit this servicio", edit_servicio_path(@servicio) %> |
  <%= link_to "Back to servicios", servicios_path %>

  <%= button_to "Destroy this servicio", @servicio, method: :delete %>
</div>

app/views/shared/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if(!current_doctor) %>
            <li class="nav-item">
            <%= link_to 'Sign Up', new_doctor_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign In', new_doctor_session_path, class:"nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Servicios", servicios_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Especialidad", especialidads_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Edit", edit_doctor_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Out", destroy_doctor_session_path, method: :delete, class:"nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>